spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_core
    username: root
    password: 123
  redis:
    host: localhost
    password:
    port: 6379
  jpa:
    show-sql: true

#logging
logging:
  level:
    root: warn
    org:
      springframework:
        security: debug
    com.tenhs: debug